### ISSUE TITLE
常用命令乱码

### ISSUE THREAD

**Issue by Tukali** [f0ng/poc2jar#1]
打开后发现常用命令乱码
![image](https://user-images.githubusercontent.com/45891208/142538568-ab5a2a19-9504-4945-8416-2bdf8ae7d56a.png)

**Comment by f0ng** [comment]
应该是windows下的吧，可以尝试使用命令
`java -jar -Dfile.encoding=utf-8 poc2jar.jar`
启动
![image](https://user-images.githubusercontent.com/48286013/142572197-fa20ca59-23cd-4109-b8ae-df14a2d7ea28.png)

**Comment by f0ng** [comment]
0.43版本更新了一下，师傅试试呢，双击就行了，不需要命令行打开了

**Comment by Tukali** [comment]
> 0.43版本更新了一下，师傅试试呢，双击就行了，不需要命令行打开了

师傅牛皮！！！，已经好了，我之前用sublime改文件编码utf-8不管用，估计是我改的不对，太感谢师傅了

**Comment by f0ng** [comment]
感谢提交issue~
