### ISSUE TITLE
一个小建议~

### ISSUE THREAD

**Issue by york-cmd** [f0ng/poc2jar#13]
师傅工具非常使用，提个小建议~
Druid未授权漏洞利用，如果是Druid弱口令登录进去，可否加个cookie或用户名密码认证，进行敏感信息提取。

**Comment by f0ng** [comment]
感谢师傅反馈，将在下个版本更新

**Comment by f0ng** [comment]
`0.60`版本增加该功能

**Comment by f0ng** [comment]
感谢师傅反馈，将在下个版本更新



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月10日(周二) 下午3:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [f0ng/poc2jar] 一个小建议~ (Issue #13)




 
师傅工具非常使用，提个小建议~
 Druid未授权漏洞利用，如果是Druid弱口令登录进去，可否加个cookie或用户名密码认证，进行敏感信息提取。
