### ISSUE TITLE
常用命令乱码了

### ISSUE THREAD

**Issue by teamtopkarl** [f0ng/poc2jar#14]
![5](https://user-images.githubusercontent.com/18065690/169727002-248a8530-4def-4318-8752-bf0dd2881af9.png)

**Comment by f0ng** [comment]
更改一下`property/cmdlists.txt`的文件编码，改成gb2312

**Comment by f0ng** [comment]
压缩包内源文件为utf-8下的文件，记事本打开是乱码，但是`poc2jar.jar`内可以正常读取；如果想自行更改，可以将`cmdlists.txt`文件以`gb2312`形式打开，为明文，再将文本通过`记事本`以`ANSI`格式保存即可
