### ISSUE TITLE
0.46无法运行

### ISSUE THREAD

**Issue by Tukali** [f0ng/poc2jar#2]
windows11,java8环境
师傅，运行的时候报错，报错信息如下：
![image](https://user-images.githubusercontent.com/45891208/143514280-89c18750-d2ad-48e6-9177-f770d3866c83.png)
![image](https://user-images.githubusercontent.com/45891208/143514301-6e10ae8a-fd70-4943-907b-d7e8b5931cfd.png)

**Comment by f0ng** [comment]
感谢师傅报告，是迭代的时候把properties文件覆盖了😂师傅再看看呢

**Comment by Tukali** [comment]
可以运行了，谢谢师傅

**Comment by f0ng** [comment]
感谢提交issue~
