### ISSUE TITLE
0.5.2无法运行：找不到或无法加载主类

### ISSUE THREAD

**Issue by Valerian7** [f0ng/poc2jar#7]
![image](https://user-images.githubusercontent.com/46412054/148642013-a0f77d06-8f67-425b-8548-958129a3410c.png)
报错：
      /**
        错误: 找不到或无法加载主类 main.Main
        原因: java.lang.NoClassDefFoundError: javafx/application/Application
      */
麻烦师傅重新打包一下

**Comment by f0ng** [comment]
没有呀，我这边下载0.52打开是正常的

![image](https://user-images.githubusercontent.com/48286013/148642361-197d6129-bac7-43ed-af80-e884721c9b05.png)
这边我查看了一下，是jdk版本的原因，jdk在11以上貌似就打不开了(10还是可以打开的)，mac可以设置一下低版本jdk为默认的，然后高版本的一些java应用可以指定高版本jdk打开
![image](https://user-images.githubusercontent.com/48286013/148642511-91f643ed-b125-4a3d-a11d-5b5bf1ea0a7b.png)

**Comment by Valerian7** [comment]
好的好的，换低版本的jdk没问题了，谢谢师傅

**Comment by f0ng** [comment]
感谢师傅反馈，有问题可以继续提issue
