### ISSUE TITLE
解密功能错误

### ISSUE THREAD

**Issue by SummerSec** [f0ng/poc2jar#8]
![image](https://user-images.githubusercontent.com/47944478/150105811-093bc467-dd50-40e6-88e4-92d0b551f603.png)
很明显功能没有生效。
![image](https://user-images.githubusercontent.com/47944478/150105918-3cc8d934-8c9f-461f-a405-83b40427ea53.png)

**Comment by f0ng** [comment]
感谢师傅反馈，`0.54`版本修复该问题，并添加gcm解密
